import jsPDF from "jspdf"

export function generateEvidencePDF({
  fileName,
  fileSize,
  localHash,
  blockchainHash,
  matchStatus,
  verifiedAt,
  capturedImage,
}: {
  fileName: string
  fileSize: string
  localHash: string
  blockchainHash?: string | null
  matchStatus: string
  verifiedAt: string
  capturedImage?: string
}) {
  const doc = new jsPDF()

  doc.setFontSize(18)
  doc.text("Evidence Verification Report", 14, 20)

  doc.setFontSize(12)
  doc.text("File Details", 14, 35)
  doc.text(`File Name: ${fileName}`, 14, 43)
  doc.text(`File Size: ${fileSize}`, 14, 50)
  doc.text(`Local SHA-256 Hash: ${localHash}`, 14, 57)

  if (blockchainHash)
    doc.text(`Blockchain Hash: ${blockchainHash}`, 14, 64)

  doc.text(`Verification Status: ${matchStatus}`, 14, 78)
  doc.text(`Verified At: ${verifiedAt}`, 14, 85)

  if (capturedImage) {
    try {
      doc.text("Captured Evidence Image:", 14, 100)
      doc.addImage(capturedImage, "PNG", 14, 105, 80, 60)
    } catch (err) {
      console.error("Image add failed", err)
    }
  }

  doc.setFontSize(10)
  doc.text("Auto-generated by ForenChain © 2025", 14, 190)
  doc.save(`Evidence_Report_${fileName}.pdf`)
}
