// // import jsPDF from "jspdf"

// // export function generateEvidencePDF({
// //   fileName,
// //   fileSize,
// //   localHash,
// //   blockchainHash,
// //   matchStatus,
// //   verifiedAt,
// //   capturedImage,
// // }: {
// //   fileName: string
// //   fileSize: string
// //   localHash: string
// //   blockchainHash?: string | null
// //   matchStatus: string
// //   verifiedAt: string
// //   capturedImage?: string
// // }) {
// //   const doc = new jsPDF()

// //   doc.setFontSize(18)
// //   doc.text("Evidence Verification Report", 14, 20)

// //   doc.setFontSize(12)
// //   doc.text("File Details", 14, 35)
// //   doc.text(`File Name: ${fileName}`, 14, 43)
// //   doc.text(`File Size: ${fileSize}`, 14, 50)
// //   doc.text(`Local SHA-256 Hash: ${localHash}`, 14, 57)

// //   if (blockchainHash)
// //     doc.text(`Blockchain Hash: ${blockchainHash}`, 14, 64)

// //   doc.text(`Verification Status: ${matchStatus}`, 14, 78)
// //   doc.text(`Verified At: ${verifiedAt}`, 14, 85)

// //   if (capturedImage) {
// //     try {
// //       doc.text("Captured Evidence Image:", 14, 100)
// //       doc.addImage(capturedImage, "PNG", 14, 105, 80, 60)
// //     } catch (err) {
// //       console.error("Image add failed", err)
// //     }
// //   }

// //   doc.setFontSize(10)
// //   doc.text("Auto-generated by ForenChain © 2025", 14, 190)
// //   doc.save(`Evidence_Report_${fileName}.pdf`)
// // }



// import jsPDF from "jspdf";

// export function generateEvidencePDF({
//   fileName,
//   fileSize,
//   localHash,
//   blockchainHash,
//   matchStatus,
//   verifiedAt,
//   capturedImage,
//   cid, // ✅ NEW
// }: {
//   fileName: string;
//   fileSize: string;
//   localHash: string;
//   blockchainHash?: string | null;
//   matchStatus: string;
//   verifiedAt: string;
//   capturedImage?: string;
//   cid?: string; // ✅ NEW
// }) {
//   const doc = new jsPDF();

//   doc.setFontSize(18);
//   doc.text("Evidence Verification Report", 14, 20);

//   doc.setFontSize(12);
//   doc.text("File Details", 14, 35);
//   doc.text(`File Name: ${fileName}`, 14, 43);
//   doc.text(`File Size: ${fileSize}`, 14, 50);
//   doc.text(`Local SHA-256 Hash: ${localHash}`, 14, 57);

//   if (blockchainHash)
//     doc.text(`Blockchain Hash: ${blockchainHash}`, 14, 64);

//   // ✅ Add CID if present
//   if (cid)
//     doc.text(`IPFS Evidence CID: ${cid}`, 14, 71);

//   doc.text(`Verification Status: ${matchStatus}`, 14, 85);
//   doc.text(`Verified At: ${verifiedAt}`, 14, 92);

//   // Evidence Image
//   if (capturedImage) {
//     try {
//       doc.text("Captured Evidence Image:", 14, 110);
//       doc.addImage(capturedImage, "PNG", 14, 115, 80, 60);
//     } catch (err) {
//       console.error("Image add failed", err);
//     }
//   }

//   doc.setFontSize(10);
//   doc.text("Auto-generated by ForenChain © 2025", 14, 190);

//   doc.save(`Evidence_Report_${fileName}.pdf`);
// }


// // import jsPDF from "jspdf";

// // export async function generateEvidencePDF({
// //   fileName,
// //   fileSize,
// //   localHash,
// //   blockchainHash,
// //   matchStatus,
// //   verifiedAt,
// //   capturedImage,
// //   cid,
// // }: {
// //   fileName: string;
// //   fileSize: string;
// //   localHash: string;
// //   blockchainHash?: string | null;
// //   matchStatus: string;
// //   verifiedAt: string;
// //   capturedImage?: string;
// //   cid?: string;
// // }) {
// //   const doc = new jsPDF();
// //   let y = 20;

// //   // Title
// //   doc.setFontSize(18);
// //   doc.text("Evidence Verification Report", 14, y);
// //   y += 10;

// //   doc.setFontSize(12);
// //   doc.text("File Details", 14, y);
// //   y += 8;
// //   doc.text(`File Name: ${fileName}`, 14, y); y += 7;
// //   doc.text(`File Size: ${fileSize}`, 14, y); y += 7;
// //   doc.text(`Local SHA-256 Hash: ${localHash}`, 14, y); y += 7;

// //   if (blockchainHash) {
// //     doc.text(`Blockchain Hash: ${blockchainHash}`, 14, y);
// //     y += 7;
// //   }

// //   if (cid) {
// //     const ipfsUrl = `https://ipfs.io/ipfs/${cid}`;
// //     doc.text(`IPFS Evidence CID: ${cid}`, 14, y); 
// //     y += 7;
// //     doc.textWithLink("🔗 View Evidence on IPFS", 14, y, { url: ipfsUrl });
// //     y += 12;

// //     try {
// //       // ✅ Generate QR code image for the IPFS URL
// //       const qrDataUrl = await QRCode.toDataURL(ipfsUrl, { margin: 1, width: 100 });
// //       doc.addImage(qrDataUrl, "PNG", 150, 30, 45, 45);
// //     } catch (err) {
// //       console.error("QR generation failed", err);
// //     }
// //   }

// //   doc.text(`Verification Status: ${matchStatus}`, 14, y); y += 7;
// //   doc.text(`Verified At: ${verifiedAt}`, 14, y); y += 10;

// //   // ✅ Add captured image if available
// //   if (capturedImage) {
// //     try {
// //       doc.text("Captured Evidence Image:", 14, y);
// //       y += 5;
// //       doc.addImage(capturedImage, "PNG", 14, y, 100, 70);
// //       y += 80;
// //     } catch (err) {
// //       console.error("Image add failed", err);
// //       doc.text("⚠️ Error adding image", 14, y);
// //       y += 10;
// //     }
// //   }

// //   doc.setFontSize(10);
// //   doc.text("Auto-generated by ForenChain © 2025", 14, 285);

// //   doc.save(`Evidence_Report_${fileName}.pdf`);
// // }


import jsPDF from "jspdf";

export function generateEvidencePDF({
  fileName,
  fileSize,
  localHash,
  blockchainHash,
  matchStatus,
  verifiedAt,
  capturedImage,
  browser,
  device,
  resolution,
  location,
}: {
  fileName: string;
  fileSize: string;
  localHash: string;
  blockchainHash?: string | null;
  matchStatus: string;
  verifiedAt: string;
  capturedImage?: string;
  browser?: string;
  device?: string;
  resolution?: string;
  location?: { lat: number; lng: number } | undefined;
}) {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.text("Evidence Verification Report", 14, 20);

  doc.setFontSize(12);
  doc.text("File Details", 14, 35);
  doc.text(`File Name: ${fileName}`, 14, 43);
  doc.text(`File Size: ${fileSize}`, 14, 50);
  doc.text(`Local SHA-256 Hash: ${localHash}`, 14, 57);

  if (blockchainHash)
    doc.text(`Blockchain Hash: ${blockchainHash}`, 14, 64);

  doc.text(`Verification Status: ${matchStatus}`, 14, 78);
  doc.text(`Verified At: ${verifiedAt}`, 14, 85);

  // ✅ Metadata Section
  doc.text("Capture Metadata", 14, 100);
  doc.text(`Device: ${device || "Unknown"}`, 14, 108);
  doc.text(`Browser: ${browser || "Unknown"}`, 14, 115);
  doc.text(`Camera Resolution: ${resolution || "Unknown"}`, 14, 122);

  if (location) {
    doc.text(
      `GPS: ${location.lat.toFixed(6)}, ${location.lng.toFixed(6)}`,
      14,
      129
    );
  } else {
    doc.text("GPS: Permission Denied or Unavailable", 14, 129);
  }

  // ✅ Insert Evidence Image
  if (capturedImage) {
    try {
      doc.text("Captured Evidence Image:", 14, 145);
      doc.addImage(capturedImage, "PNG", 14, 150, 85, 60);
    } catch (err) {
      console.error("Image add failed in PDF:", err);
    }
  }

  // Footer
  doc.setFontSize(10);
  doc.text("Auto-generated by ForenChain © 2025", 14, 210);

  doc.save(`Evidence_Report_${fileName}.pdf`);
}
